### ISSUE TITLE
New issue with cocoapods

### ISSUE THREAD

**Issue by andreichirkunovgoon** [rehatkathuria/SnappingSlider#13]
When trying to install I get this issue:

[!] /usr/local/bin/git clone https://github.com/rehatkathuria/SnappingSlider.git /var/folders/kr/n3d8ggbd71j7zsl3h52pdqy40000gn/T/d20160914-5188-15j253k --template= --single-branch --depth 1 --branch 1.1

Cloning into '/var/folders/kr/n3d8ggbd71j7zsl3h52pdqy40000gn/T/d20160914-5188-15j253k'...
warning: Could not find remote branch 1.1 to clone.
fatal: Remote branch 1.1 not found in upstream origin

**Comment by rehatkathuria** [comment]
There have been a few complications that have arisen with CocoaPods. Please install the component as a git submodule for now. I'll repair the link with CocoaPods in the near future.
