### ISSUE TITLE
Hold Slider Down To Increment/Decrement Values

### ISSUE THREAD

**Issue by rehatkathuria** [rehatkathuria/SnappingSlider#4]
I've been toying with the idea of allowing the slider to continue incrementing or decrementing the value until the user releases the touch from the slider. This functionality could be toggled with a boolean. What does the community think? Would you guys like to see this? 

cc @ashfurrow.

**Comment by ashfurrow** [comment]
Makes sense to me :+1:

**Comment by rehatkathuria** [comment]
https://github.com/rehatkathuria/SnappingSlider/commit/5facdda7df449bfaa644461aefd173a86bd8a193

**Comment by fgrosjean** [comment]
When I turn this value "shouldContinueAlteringValueUntilGestureCancels" to true I get an error: unrecognized selector sent to instance 0x7faaf55116d0

**Comment by rehatkathuria** [comment]
Can you share code please @fgrosjean? I cannot seem to recreate the issue.

**Comment by fgrosjean** [comment]
Thanks @rehatkathuria, I fixed this error by replacing NSSelectorFromString/#selector in:

`
if shouldContinueAlteringValueUntilGestureCancels {
    valueChangingTimer = Timer.scheduledTimer(timeInterval: 0.7, target: self, selector: NSSelectorFromString("handleTimer:"), userInfo: nil, repeats: true)
}`

`
if shouldContinueAlteringValueUntilGestureCancels {
    valueChangingTimer = Timer.scheduledTimer(timeInterval: 0.7, target: self, selector: #selector("handleTimer:"), userInfo: nil, repeats: true)
}`

I think Swift 4 doesn't like old objc api's. Thank you anyways, great slider you got here!
