### ISSUE TITLE
changing position of slider.

### ISSUE THREAD

**Issue by keji96** [rehatkathuria/SnappingSlider#7]
Hi: thanks for the great slider. I am using it in my app. I have one slight issue. I cant seem to change the code to move it to the top of my app. No matter which CGrect I change the slider is always in the center vertically and horizontally. Any help would be greatly appreciated.

**Comment by rehatkathuria** [comment]
Can you please post a gist of the class implementing the slider?

**Comment by keji96** [comment]
Attachment available until Aug 6, 2015
Thank you for your response I am relatively new to swift. I have attached my code here . the snapped slider is included in the ReviewViewController.swift file. It is in the view did load method.

regards. 

kevin

**Comment by rehatkathuria** [comment]
The class you're implementing the slider on has two instances of the slider. Remove the local initialiser inside the viewDidLoad and set the frame and centre inside of the viewDidLayoutSubviews() function of the viewController.

**Comment by keji96** [comment]
thank you.
