### ISSUE TITLE
SnappingSlider inside TableViewCell

### ISSUE THREAD

**Issue by polis80cy** [rehatkathuria/SnappingSlider#8]
Hello,

Is it possible to add a SnappingSlider instance inside a sub-classed TableViewCell? Can't figure it out.

Thanks,
Polis

**Comment by rehatkathuria** [comment]
You should be able to add the slider onto any instance of a UIView or one that inherits from it, including a UITableViewCell instance. Have a look at the README for a quick jump-in guide.
